services:
  - type: web
    name: ma-matsavinu-supabase
    env: python
    plan: free
    region: frankfurt

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
